import { describe, expect, it } from 'vitest';

import { pageToMarkdown } from '../../markdown/markdown.utils.ts';
import { extractTitle } from '../fetch.utils.ts';
import { refuseUnreadablePage } from '../readability.utils.ts';

const PAGE_URL = 'https://northmoor.example/people/';

const STATIC_PAGE =
  '<!doctype html><html><head><title>Research Themes — Northmoor University</title></head><body><h1>Research Themes</h1><p>Enquiries go to research@northmoor.example.</p></body></html>';

/** a shell whose every word arrives by script: nothing for markdown to carry */
const CLIENT_RENDERED_PAGES = {
  'client-rendered-directory':
    '<!doctype html><html><head><title>Faculty</title></head><body><div id="directory"></div><script src="/directory.js"></script></body></html>',
  'spa-marketing-site':
    '<!doctype html><html><head><title>Northmoor</title></head><body><div id="app"></div><script src="/app.js"></script></body></html>'
};

const CLOUDFRONT_REFUSAL =
  '<html><head><title>ERROR: The request could not be satisfied</title></head><body><h1>403 ERROR</h1>' +
  '<h2>The request could not be satisfied.</h2><p>Request blocked.</p><hr/><pre>Generated by cloudfront (CloudFront)</pre></body></html>';

const ORIGIN_OUTAGE =
  '<html><head><title>Maintenance</title></head><body><h1>Down for maintenance</h1><p>Back at noon.</p></body></html>';

const BOT_CHECK =
  '<html><head><title>Just a moment...</title></head><body><h1>psychology.northmoor.example</h1>' +
  '<h2>Verifying you are human. This may take a few seconds.</h2></body></html>';

const ARTICLE_ON_BOT_CHECKS = `<html><head><title>Why sites ask whether you are human</title></head><body>
  <h1>Why sites ask whether you are human</h1><p>A page reading "Verifying you are human" is a bot check.</p>
  <p>${'Scrapers strain small university servers. '.repeat(120)}</p></body></html>`;

const convert = (body: string, status = 200) => ({
  body,
  markdown: pageToMarkdown(body, PAGE_URL),
  status,
  title: extractTitle(body),
  url: PAGE_URL
});

describe('refuseUnreadablePage', () => {
  it('should admit a page with static content', () => {
    expect(refuseUnreadablePage(convert(STATIC_PAGE))).toBeUndefined();
  });

  it.each(Object.entries(CLIENT_RENDERED_PAGES))('should refuse %s, which reads as nothing', (_name, html) => {
    expect(refuseUnreadablePage(convert(html))).toStrictEqual({ kind: 'no-static-content', status: 200, url: PAGE_URL });
  });

  it('should read an error status with nothing readable as the error it is', () => {
    expect(refuseUnreadablePage(convert('<html></html>', 404))).toStrictEqual({
      bodyChars: 13,
      kind: 'http-error',
      status: 404,
      url: PAGE_URL
    });
  });

  it.each([401, 403, 429])('should refuse a %i as blocked, whatever its body says (§3.4)', (status) => {
    expect(refuseUnreadablePage(convert(CLOUDFRONT_REFUSAL, status))).toStrictEqual({ kind: 'blocked', status, url: PAGE_URL });
  });

  it("should refuse a 503 as blocked only where a CDN's refusal page answered it (§3.4)", () => {
    expect(refuseUnreadablePage(convert(CLOUDFRONT_REFUSAL, 503))).toMatchObject({ kind: 'blocked' });
    expect(refuseUnreadablePage(convert(ORIGIN_OUTAGE, 503))).toBeUndefined();
  });

  it('should refuse a bot check served as a success, and admit a page about one (§3.4)', () => {
    expect(refuseUnreadablePage(convert(BOT_CHECK))).toStrictEqual({ kind: 'blocked', status: 200, url: PAGE_URL });
    expect(refuseUnreadablePage(convert(ARTICLE_ON_BOT_CHECKS))).toBeUndefined();
  });
});
