import type { WebFailure } from '../web.types.ts';
import type { ConvertedPage } from './fetch.types.ts';

/** what a site answers a client it will not serve, whatever the body then says */
const REFUSAL_STATUSES: ReadonlySet<number> = new Set([401, 403, 429]);

/** a CDN refuses with this as often as an origin fails with it, so only the CDN's own page tells the two apart */
const CDN_REFUSAL_STATUS = 503;

/** the marks a CDN or firewall leaves on the page it answers with in the origin's place */
const CDN_SIGNATURES = [
  'cloudflare ray id',
  'errors.edgesuite.net',
  'generated by cloudfront',
  'incapsula incident id',
  'performance & security by cloudflare',
  'sucuri website firewall'
];

/** what a bot check says in the page's place, at whatever status it was served with */
const INTERSTITIAL_PHRASES = [
  'attention required! | cloudflare',
  'checking if the site connection is secure',
  'checking your browser before accessing',
  'confirm you are a human',
  'enable javascript and cookies to continue',
  'just a moment...',
  "making sure you're not a bot",
  'vercel security checkpoint',
  'verifying you are human'
];

/** a bot check is a line or two of text; a page longer than this that carries one of its phrases is about one */
const INTERSTITIAL_MAX_CHARS = 4_000;

function carriesAny(page: ConvertedPage, phrases: readonly string[]): boolean {
  const text = `${page.title}\n${page.markdown}`.toLowerCase();
  return phrases.some((phrase) => text.includes(phrase));
}

function isRefusal(page: ConvertedPage): boolean {
  if (REFUSAL_STATUSES.has(page.status)) {
    return true;
  }
  if (page.status === CDN_REFUSAL_STATUS && carriesAny(page, CDN_SIGNATURES)) {
    return true;
  }
  return page.markdown.length <= INTERSTITIAL_MAX_CHARS && carriesAny(page, INTERSTITIAL_PHRASES);
}

/**
 * The one verdict on whether a fetched document is readable without a browser (§3.4). A refusal
 * here costs the model one `navigate`; a pass on a hollow page or a bot check has it reasoning
 * over nothing, or recording a source as empty — so the bias is toward refusing, and richer
 * signals belong here and nowhere else.
 */
export function refuseUnreadablePage(
  page: ConvertedPage
): undefined | WebFailure.Blocked | WebFailure.HttpError | WebFailure.NoStaticContent {
  const { markdown, status, url } = page;
  if (isRefusal(page)) {
    return { kind: 'blocked', status, url };
  }
  if (markdown !== '') {
    return undefined;
  }
  return status >= 400
    ? { bodyChars: page.body.length, kind: 'http-error', status, url }
    : { kind: 'no-static-content', status, url };
}
